version: '3.5'
services:
  app:
    image: node:12.13-alpine
    container_name: app.dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 33000:3000
    environment:
      - HOME=/app
      - NODE_ENV=development
